apiVersion: apps/v1
kind: Deployment
metadata:
  name: safedose-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      volumes:
      - name: sa-key-volume
        secret:
          secretName: safedose-sa-key
      containers:
      - name: chat-app
        image: us-central1-docker.pkg.dev/safedose-medtracker/safedose-node-apps-repo/safedose-chat-service-image:v4
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: sa-key-volume
          mountPath: /secrets
          readOnly: true
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/key.json"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: safedose-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: safedose-secrets
              key: JWT_SECRET
        - name: GEMINI_MODEL
          value: "gemini-2.5-flash-lite"
        - name: CLIENT_ORIGIN
          value: "https://safedose-jet.vercel.app"

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
